%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 809.0540
Camera1.fy: 808.9344
Camera1.cx: 775.6627
Camera1.cy: 595.0128

Camera1.k1: -0.0575
Camera1.k2: 0.1311
Camera1.k3: -0.0705
Camera1.p1: -0.0015
Camera1.p2: 0.0010

Camera2.fx: 805.2300
Camera2.fy: 804.9663
Camera2.cx: 781.3354
Camera2.cy: 596.5872

Camera2.k1: -0.0578 
Camera2.k2: 0.1313 
Camera2.k3: -0.0693
Camera2.p1: -0.0015 
Camera2.p2: 6.5700e-04

Camera.width: 1600
Camera.height: 1200

# Camera frames per second 
Camera.fps: 30  
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 40.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1.0000, -0.0002, 0.0083,-247.6394e-3,
         0.0002,1.0000,0.0019, 0.2959e-3,
         -0.0083,-0.0019, 1.0000, 3.0479e-3,
         0,0,0,1.000000000000000]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 5

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast	
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 4

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0